"""initial_schema

Revision ID: 8834de17870f
Revises:
Create Date: 2026-06-08 17:29:12.531815

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8834de17870f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leagues",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("league_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("abbreviation", sa.String(length=10), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("conference", sa.String(length=50), nullable=True),
        sa.Column("division", sa.String(length=50), nullable=True),
        sa.Column(
            "external_id",
            sa.String(length=50),
            nullable=True,
            comment="ID from external data provider",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["leagues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_teams_league_abbreviation", "teams", ["league_id", "abbreviation"], unique=True
    )
    op.create_table(
        "fixtures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("league_id", sa.UUID(), nullable=False),
        sa.Column("home_team_id", sa.UUID(), nullable=False),
        sa.Column("away_team_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("season", sa.String(length=20), nullable=False),
        sa.Column(
            "week", sa.Integer(), nullable=True, comment="Applicable for NFL weekly schedule"
        ),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.Column("external_id", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["leagues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_fixtures_scheduled", "fixtures", ["league_id", "scheduled_at"], unique=False
    )
    op.create_index("ix_fixtures_status", "fixtures", ["status"], unique=False)
    op.create_table(
        "historical_stats",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fixture_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("player_name", sa.String(length=150), nullable=True),
        sa.Column(
            "stat_type",
            sa.String(length=50),
            nullable=False,
            comment="e.g. passing_yards, rebounds, hits",
        ),
        sa.Column("stat_value", sa.Float(), nullable=False),
        sa.Column(
            "boxscore_data",
            postgresql.JSON(astext_type=Text()),
            nullable=True,
            comment="Full boxscore payload for extended metrics",
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_stats_fixture_team", "historical_stats", ["fixture_id", "team_id"], unique=False
    )
    op.create_index("ix_stats_player", "historical_stats", ["player_name"], unique=False)
    op.create_table(
        "market_odds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fixture_id", sa.UUID(), nullable=False),
        sa.Column("sportsbook", sa.String(length=50), nullable=False),
        sa.Column(
            "market_type",
            sa.String(length=30),
            nullable=False,
            comment="spread, moneyline, over_under, player_prop",
        ),
        sa.Column(
            "selection",
            sa.String(length=150),
            nullable=False,
            comment="e.g. team name, Over, player name",
        ),
        sa.Column(
            "line", sa.Float(), nullable=True, comment="Spread or total value, null for moneyline"
        ),
        sa.Column("odds_american", sa.Integer(), nullable=False),
        sa.Column("odds_decimal", sa.Float(), nullable=True),
        sa.Column("vig", sa.Float(), nullable=True, comment="Calculated vig/juice percentage"),
        sa.Column(
            "prop_description",
            sa.Text(),
            nullable=True,
            comment="Player prop detail, e.g. 'Patrick Mahomes Over 275.5 Passing Yards'",
        ),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_odds_captured", "market_odds", ["captured_at"], unique=False)
    op.create_index(
        "ix_odds_fixture_book_market",
        "market_odds",
        ["fixture_id", "sportsbook", "market_type"],
        unique=False,
    )
    op.create_table(
        "model_predictions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fixture_id", sa.UUID(), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("model_version", sa.String(length=30), nullable=False),
        sa.Column("predicted_home_score", sa.Float(), nullable=True),
        sa.Column("predicted_away_score", sa.Float(), nullable=True),
        sa.Column("home_win_probability", sa.Float(), nullable=True),
        sa.Column("away_win_probability", sa.Float(), nullable=True),
        sa.Column("predicted_total", sa.Float(), nullable=True),
        sa.Column(
            "edge_vs_market",
            sa.Float(),
            nullable=True,
            comment="Calculated edge: our probability minus implied market probability",
        ),
        sa.Column(
            "ev_percentage",
            sa.Float(),
            nullable=True,
            comment="Expected value as a percentage of stake",
        ),
        sa.Column(
            "prediction_metadata",
            postgresql.JSON(astext_type=Text()),
            nullable=True,
            comment="Additional prediction context and feature importances",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_predictions_ev", "model_predictions", ["ev_percentage"], unique=False)
    op.create_index(
        "ix_predictions_fixture_model",
        "model_predictions",
        ["fixture_id", "model_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_predictions_fixture_model", table_name="model_predictions")
    op.drop_index("ix_predictions_ev", table_name="model_predictions")
    op.drop_table("model_predictions")
    op.drop_index("ix_odds_fixture_book_market", table_name="market_odds")
    op.drop_index("ix_odds_captured", table_name="market_odds")
    op.drop_table("market_odds")
    op.drop_index("ix_stats_player", table_name="historical_stats")
    op.drop_index("ix_stats_fixture_team", table_name="historical_stats")
    op.drop_table("historical_stats")
    op.drop_index("ix_fixtures_status", table_name="fixtures")
    op.drop_index("ix_fixtures_scheduled", table_name="fixtures")
    op.drop_table("fixtures")
    op.drop_index("ix_teams_league_abbreviation", table_name="teams")
    op.drop_table("teams")
    op.drop_table("leagues")
    # ### end Alembic commands ###
